[package]
name = "shape3d"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.29.1"
rayon = "1.10.0"
libloading = "0.8.5"
shape3d_common = { path = "common" }
